CREATE SCHEMA DEMO;
CREATE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

CREATE MASKING POLICY email_visibility AS
(val string) RETURNS string ->
 CASE
   WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN val
   ELSE '*****'
 END ;
